networks:
  network:
    name: network
    external: true

services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/public_html
    networks:
      - network
    depends_on:
      - php

  php:
    container_name: php
    build: ./images/php
    volumes:
      - ./www:/var/www/public_html
    networks:
      - network
